S/*======================================================================================================================
													Design Specs
													
o MAX_GAME_TYPES
	- This corresponds to the game set, like Doom or Chex
o MAX_ALTS
	- This corresponds to a game alt set, like Opposing Force
o MONSTER_SLOT
	- This corresponds to the monster slot, like Zombieman. Slots are in this order:
										0: 	Zombieman
										1: 	Shotgunguy
										2: 	Imp
										3: 	Chaingunner
										4: 	Demon
										5: 	Spectre
										6: 	Hellknight
										7: 	Baron of Hell
										8: 	Arachnotron
										9: 	Mancubus
										10: Lost Soul
										11: Pain Elemental
										12: Cacodemon
										13: Revenant
										14: Archvile
										15: Cyberdemon
										16: Spider Mastermind
										17: Wolfenstein SS
										18: Super Shotgunguy
										19: Dark Imp
										20: Blood Demon
										21: Cacolantern
										22: Abaddon
										23: Hectebus
										24: Belphegor
o MAXPERSLOT
	- This variable is the slot for a decision on the monster from the slot, like spawning a zombieman variant
			
													- Strings -
	o Monster name:
		- Name of the the monster
	o Token0-4:
		- These are inventory items that can be given to a monster for each difficulty, to alter their behavior
		
													- Stats -
	o Speed0-4:
		- These tokens work as a multiplier for monster speed. As such, you should never use numbers with no decimal
		decimal point. Please use 2.0 instead of 2. If left alone, it will have no affect.
	o Health0-4:
		- A health multiplier. Same as speed, these are multipliers. If left alone, it will have no affect.
	o Weight0-4:
		- This is a spawn chance, which functions similarly to RandomSpawner. You can use whatever numbers you want,
		to define the chance of a monster spawning. The higher the weight compared to other monsters, the more likely
		it is to spawn, and vice versa. If left alone, will be treated as 1. If set to a negative value, however,
		that means the monster will not spawn at all on that difficulty.

======================================================================================================================*/
//Monster name, 										token0, 									token1, 									token2, 								token3, 								token4						token5
int monsterSelectStr[MAX_GAME_TYPES][MAX_ALTS][MONSTER_SLOT][MAXPERSLOT][6] = 
{	
	{//Doom
		{//Classic
			{//Zombieman
				{ "Zombieman3" }
			},
			{//Shotgunguy
				{ "Shotgunguy3" }
			},
			{//Doom Imp
				{ "DoomImp3" }
			},
			{//Chaingunguy
				{ "Chaingunguy3" }
			},
			{//Demon
				{ "DoomDemon3" }
			},
			{//Spectre
				{ "Spectre3" }
			},
			{//Hell Knight
				{ "HellKnight3" }
			},
			{//Baron of Hell
				{ "BaronofHell3" }
			},
			{//Arachnotron
				{ "Arachnotron3" }
			},
			{//Mancubus
				{ "Fatso3" }
			},
			{
				{ "LostSoul3" }
			},
			{
				{ "PainElemental3" }
			},
			{
				{ "Cacodemon3" }
			},
			{
				{ "Revenant3" }
			},
			{
				{ "Archvile3" }
			},
			{
				{ "Cyberdemon3" }
			},
			{
				{ "SpiderMastermind3" }
			},
			{
				{ "Nazi3" }
			},
			{
				{ "SuperShotgunguy2" }
			},
			{
				{ "DarkImp2" }
			},
			{
				{ "BloodDemon2" }
			},
			{
				{ "Cacolantern2" }
			},
			{
				{ "Abaddon2" }
			},
			{
				{ "Hectebus2" }
			},
			{
				{ "Belphegor2" }
			}
		},
		{	//64
			{
				{ "Zombieman64" }
			},
			{
				{ "Shotgunguy64" }
			},
			{
				{ "DoomImp64" },
				{ "NightmareImp64" }
			},
			{
				{ "Chaingunguy64" }
			},
			{
				{ "Demon64" }
			},
			{
				{ "Spectre64" }
			},
			{
				{ "HellKnight64" }
			},
			{
				{ "BaronofHell64" }
			},
			{
				{ "Arachnotron64" }
			},
			{
				{ "Fatso64" }
			},
			{
				{ "LostSoul64" }
			},
			{
				{ "PainElemental64" }
			},
			{
				{ "Cacodemon64" }
			},
			{
				{ "Revenant64" }
			},
			{
				{ "Archvile64" }
			},
			{
				{ "Cyberdemon64" }
			},
			{
				{ "SpiderMastermind64" },
				{ "MotherDemon64" }
			},
			{
				{ "WolfensteinSSJagaur" }
			}
		},
		{	//VDR
			{
				{ "ZombieManRandomizer" }
			},
			{
				{ "ShotgunguyRandomizer" }
			},
			{
				{ "DoomImpRandomizer" }
			},
			{
				{ "ChaingunguyRandomizer" }
			},
			{
				{ "DoomDemonRandomizer" }
			},
			{
				{ "SpectreRandomizer" }
			},
			{
				{ "HellKnightRandomizer" }
			},
			{
				{ "BaronofHell3" },
				{ "MMRandomizer_HellsFury" }, 
				{ "MMRandomizer_CyberBaron" },
				{ "MMRandomizer_BruiserDemon" },
				{ "MMRandomizer_Belphegor" },
			},
			{
				{ "Arachnotron3" }, 
				{ "MMRandomizer_ChaingunArachnotron" }, 
				{ "MMRandomizer_RailgunArachnotron" },
			},
			{
				{ "Fatso3" }, 
				{ "MMRandomizer_Cryocubus" }, 
				{ "MMRandomizer_Hectebus" },
			},
			{
				{ "LostSoulRandomizer" }
			},
			{
				{ "PainElementalRandomizer" }
			},
			{
				{ "CacodemonRandomizer" }
			},
			{
				{ "RevenantRandomizer" }
			},
			{
				{ "ArchvileRandomizer" }
			},
			{
				{ "Cyberdemon3" }, 
				{ "MMRandomizer_ArchonOfHell" }, 
				{ "MMRandomizer_Annihilator" },
			},
			{
				{ "SpiderMastermind3" }, 
				{ "MMRandomizer_ArachnorbQueen" }, 
				{ "MMRandomizer_Demolisher" },
			},
			{
				{ "Nazi3" }
			}
		}
	},
	{//Chex
		{//Main
			{//Zombieman
				{ "FlemoidusCommonus3" }
			},
			{
				{ "FlemoidusBipedicus3" }
			},
			{
				{ "NewArmoredFlemoidusBipedicus" }
			},
			{
				{ "NewArmoredFlemoidusBipedicus" }
			},
			{
				{ "NewFlemoidusStridicus" }
			},
			{
				{ "NewFlemoidusCycloptisCommonus" }, 
				{ "NewLarva" }
			},
			{
				{ "NewQuadrumpus" }
			},
			{
				{ "OldFlemoidusMaximusDoom" }
			},
			{
				{ "NewQuadrumpus" }
			},
			{
				{ "NewQuadrumpus" }
			},
			{
				{ "FlemMine2" }, 
				{ "NewFlemoidusGyro" }
			},
			{
				{ "SuperCycloptis2" }
			},
			{
				{ "SuperCycloptis2" }
			},
			{
				{ "NewQuadrumpus" }
			},
			{
				{ "NewSnotfolus" }
			},
			{
				{ "FlembominationNew" }
			},
			{
				{ "YellowArmoredFlemoid" }
			}
		}
	},
	{//Heretic
		{//Main
			{
				{ "Mummy3Doom" }
			},
			{
				{ "MummyLeader3Doom" }
			},
			{
				{ "HereticImpLeader3" }
			},
			{
				{ "Knight3Doom" }
			},
			{
				{ "Clink3Doom" }
			},
			{
				{ "KnightGhost3Doom" }, 
				{ "MummyGhost3Doom" },
				{ "MummyLeaderGhost3Doom" },
			},
			{
				{ "Beast3Doom" }
			},
			{
				{ "Beast3Doom" }
			},
			{
				{ "Snake3Doom" }
			},
			{
				{ "Beast3Doom" }
			},
			{
				{ "HereticImp3" }
			},
			{
				{ "Wizard3Doom" }, 
			},
			{
				{ "Wizard3Doom" }
			},
			{
				{ "Snake3Doom" }
			},
			{
				{ "IronLich3Doom" }
			},
			{
				{ "Minotaur3" }
			},
			{
				{ "Sorcerer5" }
			},
			{
				{ "CyCloneGrunt" }
			}
		}
	},
	{//Wolf 3D
		{//Classic
			{
				{ "WolfGuard" }
			},
			{
				{ "WolfOfficer" }
			},
			{
				{ "WolfOfficer" }
			},
			{
				{ "WolfSS" }
			},
			{
				{ "WolfDog" }
			},
			{
				{ "WolfDogSpectre" }
			},
			{
				{ "WolfMutant" }
			},
			{
				{ "HansGrosseDoom" },
				{ "GretelGrosseDoom" }
			},
			{
				{ "OttoGiftmacherDoom" }
			},
			{
				{ "OttoGiftmacherDoom" }
			},
			{
				{ "WolfSpectre" }
			},
			{
				{ "FakeHitler" }
			},
			{
				{ "FakeHitler" }
			},
			{
				{ "WolfMutant" }
			},
			{
				{ "TransGrosseDoom" }
			},
			{
				{ "DoctorSchabbs" },
				{ "AngelofDeath" },
				{ "BarnacleWilhelm" },
				{ "UberMutant" },
				{ "BarnacleWilhelm" }
			},
			{
				{ "GeneralFettgesicht" },
				{ "WDeathKnight" },
				{ "MechaHitler" }
			},
			{
				{ "Wolf3D_RussianRedArmy" }
			}
		},
		{//Spear of Destiny
			{
				{ "SODGuard" }
			},
			{
				{ "SODOfficer" }
			},
			{
				{ "SODOfficer" }
			},
			{
				{ "SODSS" }
			},
			{
				{ "SODDog" }
			},
			{
				{ "SODDogSpectre" }
			},
			{
				{ "SODBat" }
			},
			{
				{ "GeneralleutnantStahlkopfDoom" },
			},
			{
				{ "GerhardtVonSchreiberDoom" }
			},
			{
				{ "GerhardtVonSchreiberDoom" }
			},
			{
				{ "SODSpectre" },
				{ "SODSpectre2" }
			},
			{
				{ "FireDrone" }, 
			},
			{
				{ "FireDrone" }
			},
			{
				{ "SODBat" }
			},
			{
				{ "SubmarineWillyDoom" }
			},
			{
				{ "ProfessorQuarkblitz" },
				{ "TheAxe" }
			},
			{
				{ "Robot" },
				{ "DevilIncarnate" }
			},
			{
				{ "Wolf3D_RussianRedArmy" }
			}
		},
		{//Totenkopf SDL
			{
				{ "TotenkopfGuardSpawner" },
				{ "TotenkopfScientistSpawner" }
			},
			{
				{ "TotenkopfInfantrySpawner" }
			},
			{
				{ "TotenkopfGuardSpawner" }
			},
			{
				{ "TotenkopfSSSpawner" },
				{ "TotenkopfMutantSpawner" }
			},
			{
				{ "TotenkopfDogSpawner" }
			},
			{
				{ "TotenkopfDogSpawner" }
			},
			{
				{ "TotenkopfTrooperPanzerschreck" }
			},
			{
				{ "TotenkopfHansGrosse" }
			},
			{
				{ "TotenkopfTrooperChaingun" }
			},
			{
				{ "TotenkopfTrooperFlamethrower" }
			},
			{
				{ "TotenkopfGhost" }
			},
			{
				{ "TotenkopfMonk" }
			},
			{
				{ "TotenkopfMonk2" }
			},
			{
				{ "TotenkopfWaffenSSSpawner" }
			},
			{
				{ "TotenkopfMechanoidStormTrooper" }
			},
			{
				{ "TotenkopfSchabbsMutant" },
				{ "TotenkopfNarbengesicht" }
			},
			{
				{ "TotenkopfPanzGrosse" },
				{ "TotenkopfDeathMutant" }
			},
			{
				{ "Wolf3D_RussianRedArmy" }
			}
		}
	},
	{	//Hexen
		{//Main
			{
				{ "Ettin3Doom" }
			},
			{
				{ "Ettin3Doom" }
			},
			{
				{ "FireDemon3Doom" },
				{ "Ettin3Doom" }
			},
			{
				{ "FireDemon3Doom" }
			},
			{
				{ "Centaur3Doom" }
			},
			{
				{ "CentaurLeader3Doom" }
			},
			{
				{ "Demon1CDoom" }
			},
			{
				{ "Demon2CDoom" }
			},
			{
				{ "Dragon3Doom" }
			},
			{
				{ "IceGuy3Doom" }, 
			},
			{
				{ "FireDemon3Doom" }
			},
			{
				{ "Wraith3Doom" },
				{ "Bishop3Doom" }
			},
			{
				{ "Wraith3Doom" },
				{ "Bishop3Doom" }
			},
			{
				{ "IceGuy3Doom" }
			},
			{
				{ "ClericBoss3Doom" },
				{ "FighterBoss3Doom" },
				{ "MageBoss3Doom" }
			},
			{
				{ "Heresiarch3Doom" }
			},
			{
				{ "Korax3Doom" }
			},
			{
				{ "Pig3" }
			}
		}
	},
	{	//Duke 3D
		{//Main
			{
				{ "AssaultTrooper" }
			},
			{
				{ "PigCop" },
				{ "ZombiePigCop" },
				{ "AssaultGeneral" },
				{ "MagnumPig" },
			},
			{
				{ "AssaultCaptain" },
				{ "AssaultGeneral" },
				{ "AssaultTrooper" },
			},
			{
				{ "AssaultEnforcer" },
				{ "PiginaDress" }
			},
			{
				{ "ProtectorDroneDoom" },
				{ "ProtozoidEgg" }
			},
			{
				{ "ProtozoidEgg" },
				{ "ProtectorDroneDoom" },
			},
			{
				{ "AssaultCommander" },
				{ "PigCop" },
			},
			{
				{ "MiniBattlelordDoom" }
			},
			{
				{ "PigCopTank" }
			},
			{
				{ "ScorpionTank" }, 
			},
			{
				{ "SentryDrone" }
			},
			{
				{ "AssaultCommander" },
				{ "ReconPatrolVehicle" },
			},
			{
				{ "Octabrain" },
				{ "SharkDrone" },
			},
			{
				{ "ProtectorDroneDoom" }
			},
			{
				{ "PigCopTankArch" },
			},
			{
				{ "BattlelordDoom" },
				{ "OverlordDoom" },
			},
			{
				{ "CycloidEmperorDoom" },
				{ "AlienQueenDoom" },
				{ "CyberKeef" }
			},
			{
				{ "SentryDrone" }
			}
		},
		{//Life's a Beach
			{
				{ "BeachTrooper" },
			},
			{
				{ "BeachPig" },
				{ "BeachGeneral" },
				{ "MagnumPig" }
			},
			{
				{ "BeachCaptain" },
				{ "BeachGeneral" },
				{ "BeachTrooper" }
			},
			{
				{ "SeaMonster" },
			},
			{
				{ "ProtectorDroneDoom" },
				{ "ProtozoidEgg" }
			},
			{
				{ "ProtozoidEgg" },
				{ "ProtectorDroneDoom" },
			},
			{
				{ "BeachCommander" },
				{ "BeachPig" }
			},
			{
				{ "MiniBattlelordDoom" }
			},
			{
				{ "PigCopTank" }
			},
			{
				{ "ScorpionTank" }, 
			},
			{
				{ "SentryDrone" },
				{ "Seagull" },
			},
			{
				{ "BeachCommander" },
				{ "ReconPatrolVehicle" }
			},
			{
				{ "BeachOctabrain" },
				{ "SharkDrone" }
			},
			{
				{ "ProtectorDroneDoom" }
			},
			{
				{ "PigCopTankArch" },
			},
			{
				{ "BattlelordDoom" },
				{ "OverlordDoom" }
			},
			{
				{ "BeachCycloidEmperorDoom" },
				{ "AlienQueenDoom" },
				{ "CyberKeef" }
			},
			{
				{ "Seagull" }
			}
		}
	},
	{	//Marathon
		{//Main
			{
				{ "FighterMinor" },
				{ "ProjectileFighterMinor" },
				{ "M1FighterMinor" },
				{ "M1ProjectileFighterMinor" },
				{ "MSimulacrum" },
				{ "M2Simulacrum" }
			},
			{
				{ "ProjectileFighterMinor" },
				{ "M1ProjectileFighterMinor" },
				{ "MSimulacrum" },
				{ "M2Simulacrum" },
				{ "ProjectileFighterMajor" },
				{ "M1ProjectileFighterMajor" }
			},
			{
				{ "SewageFlickta" },
				{ "LavaFlickta" },
				{ "ProjectileFighterMajor" }				
			},
			{
				{ "TrooperMinor" },
				{ "M1TrooperMinor" },
				{ "TrooperMajor" }, 
				{ "M1TrooperMajor" }
			},
			{
				{ "FighterMajor" },
				{ "WaterFlickta" },
				{ "DrinniolMinor" },
				{ "DrinniolMajor" },
				{ "SuperFighter" }
			},
			{
				{ "WaterFlickta" },
				{ "MLooker" },
				{ "MLooker2" },				
				{ "DrinniolMinor" },
				{ "DrinniolMajor" },
				{ "SuperFighter" }
			},
			{
				{ "HunterMinor" },
				{ "M1HunterMinor" }
			},
			{
				{ "HunterMajor" },
				{ "M1HunterMajor" }	,
				{ "MotherofAllHunters" }
			},
			{
				{ "FlameCyborgMinor" }, 
				{ "FlameCyborgMajor" }, 
//				{ "MotherofAllCyborgs" }
			},			
			{
				{ "CyborgMinor" },
				{ "CyborgMajor" },
				{ "MotherofAllCyborgs" }
			},
			{
				{ "DroneMinor" },
				{ "MWasp" },
				{ "M2Tick" },
				{ "DroneMajor" },
				{ "MWasp2" },
				{ "M2TickBomb" }
			},
			{
				{ "SphtMajor" },
				{ "M1SphtMajor" },
				{ "SphtKrMinor" },
				{ "SphtKrMajor" },
				{ "MADD2" },
				{ "M2EliteSpht" }
			},
			{
				{ "SphtMinor" },
				{ "MADD1" },
				{ "M1SphtMinor" }
			},
			{
				{ "M1EnforcerMinor" },
				{ "M2EnforcerMinor" },
				{ "M1EnforcerMajor" },
				{ "M2EnforcerMajor" }
			},
			{
				{ "M2EliteEnforcerMinor" },
				{ "M2EliteEnforcerMajor" },
				{ "SuperTrooper" }
			},
			{
				{ "JuggernautMajor" },
				{ "JuggernautMinor" }
			},
			{
				{ "M1Juggernaut" }
			},
			{
				{ "Marathon_Headless" }
			}
		}
	},	
	{//Quake
		{//Main
			{
				{ "QGrunt" },
				{ "RottWeiler" }
			},	
			{
				{ "QEnforcer" }
			},
			{
				{ "QZombie" }
			},
			{
				{ "QCentroid" }
			},
			{
				{ "QKnight" },
				{ "QKStatue1" },
				{ "QGremlin" }
			},
			{
				{ "QPhantomSwordsman" },
				{ "Quake_Spawn" },
				{ "Quake_HellSpawn" },
				{ "Quake_HellSpawn_2" }
			},	
			{
				{ "QFiend" },
				{ "QGuardian" }
			},
			{
				{ "QGuardian2" },
				{ "QGuardian3" },
				{ "QGuardian4" },
				{ "QMummy" }
			},	
			{
				{ "Vore" }
			},	
			{
				{ "QHKnight" },
				{ "QKStatue2" }
			},
			{
				{ "QSpikeMine" }
			},
			{
				{ "QWrath" }
			},
			{
				{ "QScrag" }
			},
			{
				{ "QOgre" },
				{ "QMultiOgre" }
			},
			{
				{ "Shambler" },
			},	
			{
				{ "Pterodactylus" },
				{ "QArmagon" }
			},
			{
				{ "Shub-Niggurath" },
				{ "QOverlord" }
			},
			{
				{ "Zombieman3" },
			}
		}
	},	
	{//RoTT
		{//Main
			{
				{ "LowGuard" }
			},
			{
				{ "LightningGuard" }
				{ "HeavyGuard" }
			},
			{
				{ "LowGuard" }
			},
			{
				{ "HighGuard" }
			},
			{
				{ "MonkDrain_Weak" }
			},
			{
				{ "MonkDrain_Weak" }
			},
			{
				{ "RobotGuard" }
			},
			{
				{ "GeneralDarian" }
			},
			{
				{ "MonkDeathFire" }
			},
			{
				{ "Ballistikraft" }
			},
			{
				{ "ExplosiveDiskJr" }
			},
			{
				{ "CopterPatrol2" }
			},
			{
				{ "CopterPatrol" }
			},	
			{
				{ "OverPatrol" },
				{ "StrikeTeam" }
			},
			{
				{ "TriadEnforcer" }
			},
			{
				{ "TomHall" },
				{ "NME" }
			},	
			{
				{ "SnakeTom" },
				{ "SebastianKrist" }
			},
			{
				{ "WolfGaurd" }
			}
		}
	},	
	{//Blake Stone
		{//Main
			{
				{ "Informant" },
				{ "SectorGuard" },
				{ "SectorPatrol" }
			},
			{
				{ "SectorGuard" },
				{ "SectorPatrol" },
				{ "MutatedGuard" }
			},
			{
				{ "MutantBrown" }
			},
			{	
				{ "BlakeSentinel" },
				{ "TechWarrior" }
			},
			{
				{ "MutantGreen" }
			},
			{
				{ "WaterAlien" }
			},	
			{
				{ "ExpMutantBrown" },
				{ "GeneticGuard" },
				{ "PodAlien" }
			},
			{
				{ "ExpMutantBlue" },
				{ "CyborgWarrior" }
			},	
			{
				{ "SpiderMutant" }
			},
			{
				{ "AcidDragon" },
				{ "BioMech" }
			},
			{
				{ "PerScanDrone" },
				{ "PlasmaSphere" }
			},
			{
				{ "PerGunnerDrone" }
			},
			{
				{ "PerGunnerDrone" }
			},
			{
				{ "ReptilianWarrior" },
				{ "MechSentinel" },
				{ "StarTrooper" },
				{ "AlienProtector" }
			},
			{
				{ "BreatherBeast" },
				{ "PlasmaAlien" }
			},
			{
				{ "GiantStalker" },
				{ "CrawlerBeast" },
				{ "SpectorDemon" },
				{ "ArmoredStalker" }
			},
			{
				{ "GoldFire"}
			},
			{
				{ "Informant" },
			}	
		}
	},	
};